/*
 * IMatView.java
 */

package imat;

import imat.program.CategoryHandler;
import imat.program.Controller;
import imat.program.IController;
import imat.program.IMatUser;
import imat.program.IView;
import imat.program.NamedOrder;
import imat.program.PaymentInfo;
import imat.program.PaymentInfo.CardType;
import imat.program.UserHandler;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingCart;
import se.chalmers.ait.dat215.project.ShoppingCartListener;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 * The application's main frame.
 */
public class IMatView extends FrameView implements IView {

    IController controller;
    ShoppingCartListener cartListener = new ShoppingCartListener() {

        public void shoppingCartChanged() {
            //IMatDataHandler.getInstance().getShoppingCart().getItems();
            
            kundvagn.removeAll();
            
            List<ShoppingItem> items = IMatDataHandler.getInstance().getShoppingCart().getItems();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Produkt");
            dm.addColumn("Mängd");
            dm.addColumn("Pris");
            
            DefaultTableModel dm2 = new DefaultTableModel();
            dm2.addColumn("Produkt");
            dm2.addColumn("Mängd");
            dm2.addColumn("Pris/Mängd");
            dm2.addColumn("Pris");
            
            //Iterate through list 
            Iterator it = items.iterator();
            
            System.out.println( items.size() );
            
            while( it.hasNext() )
            {
                ShoppingItem i = (ShoppingItem) it.next();
                
                dm.addRow( new Object[]{
                    i.getProduct().getName(),
                    i.getAmount() + " " + i.getProduct().getUnitSuffix(),
                    i.getTotal() + " kr"}
                );
                
                dm2.addRow( new Object[]{
                    i.getProduct().getName(),
                    i.getAmount() + " " + i.getProduct().getUnitSuffix(),
                    i.getProduct().getPrice() + " kr/" + i.getProduct().getUnitSuffix(),
                    i.getTotal() + " kr"}
                );
            }
             
            kundvagn.setModel(dm);
            checkout1Cart.setModel(dm2);
            checkout3Cart.setModel(dm2);
            
            
            
        }
    };
    static IMatView view;
    private List<Product> lastProducts;
    private Product lastProduct;
    public IMatView(SingleFrameApplication app) {
        super(app);
        view = this;

        initComponents();

        this.controller = new Controller(this);
        
    }
    
    public static IMatView getView(){
        return view;
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = IMatApp.getApplication().getMainFrame();
            aboutBox = new IMatAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        IMatApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainTop = new javax.swing.JPanel();
        logoTop = new javax.swing.JLabel();
        btnButik = new javax.swing.JLabel();
        btnHistorik = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        mainBot = new javax.swing.JPanel();
        panelButik = new javax.swing.JPanel();
        butikLeft = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fieldSearch = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        butikRight = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kundvagn = new javax.swing.JTable();
        btnEmptyBasket = new javax.swing.JLabel();
        btnEmptyBasket1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        butikMid = new javax.swing.JPanel();
        midButik = new javax.swing.JPanel();
        butikSwitcher = new javax.swing.JLayeredPane();
        butikList = new javax.swing.JScrollPane();
        productWindow = new imat.productWindow();
        btnKassan = new javax.swing.JLabel();
        midLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usrName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLoginCall = new javax.swing.JButton();
        pswd = new javax.swing.JPasswordField();
        midRegister = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        surName = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        passChk = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        midHistorik = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFavCart = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fieldFavCartName = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        favCarts = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        oldCarts = new javax.swing.JList();
        addFavCart = new javax.swing.JLabel();
        removeFavCart = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panelCheckout1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        checkout1Cart = new javax.swing.JTable();
        startPayment = new javax.swing.JButton();
        checkoutProduct = new imat.productWindow();
        panelCheckout2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        payName = new javax.swing.JTextField();
        paySurname = new javax.swing.JTextField();
        payAdress = new javax.swing.JTextField();
        payPostal = new javax.swing.JTextField();
        payArea = new javax.swing.JTextField();
        payPhone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        payCardholder = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        payCard = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        payCvc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        payExpireMonth = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        payExpireYear = new javax.swing.JComboBox();
        payCardType = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        btnFinishBuy = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        payAccept = new javax.swing.JCheckBox();
        panelCheckout3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        checkout3Cart = new javax.swing.JTable();
        btnGoHome = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productWindow1 = new imat.productWindow();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(IMatView.class);
        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTop.setBackground(resourceMap.getColor("mainTop.background")); // NOI18N
        mainTop.setName("mainTop"); // NOI18N
        mainTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoTop.setIcon(resourceMap.getIcon("logoTop.icon")); // NOI18N
        logoTop.setText(resourceMap.getString("logoTop.text")); // NOI18N
        logoTop.setName("logoTop"); // NOI18N
        mainTop.add(logoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnButik.setIcon(resourceMap.getIcon("btnButik.icon")); // NOI18N
        btnButik.setName("btnButik"); // NOI18N
        btnButik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnButikMouseClicked(evt);
            }
        });
        mainTop.add(btnButik, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnHistorik.setIcon(resourceMap.getIcon("btnHistorik.icon")); // NOI18N
        btnHistorik.setText(resourceMap.getString("btnHistorik.text")); // NOI18N
        btnHistorik.setName("btnHistorik"); // NOI18N
        btnHistorik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorikMouseEntered(evt);
            }
        });
        mainTop.add(btnHistorik, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 270, -1));

        btnLogin.setIcon(resourceMap.getIcon("btnLogin.icon")); // NOI18N
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        mainTop.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 10, 270, -1));

        mainPanel.add(mainTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainBot.setName("mainBot"); // NOI18N
        mainBot.setLayout(new java.awt.CardLayout());

        panelButik.setBackground(resourceMap.getColor("panelButik.background")); // NOI18N
        panelButik.setName("panelButik"); // NOI18N
        panelButik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butikLeft.setBackground(resourceMap.getColor("butikLeft.background")); // NOI18N
        butikLeft.setName("butikLeft"); // NOI18N
        butikLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldSearch.setName("fieldSearch"); // NOI18N
        jPanel4.add(fieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 180, -1));

        jLabel29.setIcon(resourceMap.getIcon("jLabel29.icon")); // NOI18N
        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        butikLeft.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 197, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTree1.setFont(resourceMap.getFont("jTree1.font")); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Kategorier");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Favoriter");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bröd");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Fika och snacks");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fika");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Snacks");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Frukt och grönt");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Bär");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Citrusfrukter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kål");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Meloner");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nötter och frön");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Rotfrukter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Stenfrukter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ärtor och baljväxter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Örter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Övriga frukter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Övriga grönsaker");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kalla drycker");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fruktdrycker");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Läskeblask");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Kött och fisk");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fisk");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kyckling");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nötkött");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mejerivaror");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Torrvaror");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Bakning");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Drycker");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Pasta");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ris");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Övriga torrvaror");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setName("Kategorier");
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);
        jTree1.setRootVisible(false);
        jTree1.setToggleClickCount(1);

        butikLeft.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 180, 445));

        panelButik.add(butikLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        butikRight.setBackground(resourceMap.getColor("butikRight.background")); // NOI18N
        butikRight.setName("butikRight"); // NOI18N
        butikRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        kundvagn.setFont(resourceMap.getFont("kundvagn.font")); // NOI18N
        kundvagn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produkt", "Mängd", "Pris"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kundvagn.setColumnSelectionAllowed(true);
        kundvagn.setName("kundvagn"); // NOI18N
        jScrollPane2.setViewportView(kundvagn);
        kundvagn.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        kundvagn.getColumnModel().getColumn(0).setResizable(false);
        kundvagn.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("kundvagn.columnModel.title0")); // NOI18N
        kundvagn.getColumnModel().getColumn(1).setResizable(false);
        kundvagn.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("kundvagn.columnModel.title1")); // NOI18N
        kundvagn.getColumnModel().getColumn(2).setResizable(false);
        kundvagn.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("kundvagn.columnModel.title2")); // NOI18N

        butikRight.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -2, 280, 420));

        btnEmptyBasket.setIcon(resourceMap.getIcon("btnEmptyBasket.icon")); // NOI18N
        btnEmptyBasket.setText(resourceMap.getString("btnEmptyBasket.text")); // NOI18N
        btnEmptyBasket.setName("btnEmptyBasket"); // NOI18N
        btnEmptyBasket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptyBasketMouseClicked(evt);
            }
        });
        butikRight.add(btnEmptyBasket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btnEmptyBasket1.setName("btnEmptyBasket1"); // NOI18N
        btnEmptyBasket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptyBasket1MouseClicked(evt);
            }
        });
        butikRight.add(btnEmptyBasket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel26.setIcon(resourceMap.getIcon("jLabel26.icon")); // NOI18N
        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        butikRight.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        panelButik.add(butikRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 11, 310, 510));

        butikMid.setName("butikMid"); // NOI18N
        butikMid.setLayout(new java.awt.CardLayout());

        midButik.setBackground(resourceMap.getColor("midButik.background")); // NOI18N
        midButik.setMaximumSize(new java.awt.Dimension(778, 522));
        midButik.setName("midButik"); // NOI18N
        midButik.setRequestFocusEnabled(false);
        midButik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butikSwitcher.setName("butikSwitcher"); // NOI18N

        butikList.setBackground(resourceMap.getColor("butikList.background")); // NOI18N
        butikList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        butikList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        butikList.setName("butikList"); // NOI18N
        butikList.setBounds(0, 0, 760, 510);
        butikSwitcher.add(butikList, javax.swing.JLayeredPane.DEFAULT_LAYER);

        productWindow.setName("productWindow"); // NOI18N
        productWindow.setBounds(290, 10, 352, 453);
        butikSwitcher.add(productWindow, javax.swing.JLayeredPane.DEFAULT_LAYER);

        midButik.add(butikSwitcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 768, 510));

        btnKassan.setName("btnKassan"); // NOI18N
        btnKassan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKassanMouseClicked(evt);
            }
        });
        midButik.add(btnKassan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        butikMid.add(midButik, "card2");

        midLogin.setBackground(resourceMap.getColor("midLogin.background")); // NOI18N
        midLogin.setName("midLogin"); // NOI18N
        midLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        usrName.setText(resourceMap.getString("usrName.text")); // NOI18N
        usrName.setName("usrName"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        btnRegister.setText(resourceMap.getString("btnRegister.text")); // NOI18N
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLoginCall.setText(resourceMap.getString("btnLoginCall.text")); // NOI18N
        btnLoginCall.setName("btnLoginCall"); // NOI18N
        btnLoginCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCallActionPerformed(evt);
            }
        });

        pswd.setText(resourceMap.getString("pswd.text")); // NOI18N
        pswd.setName("pswd"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswd)
                            .addComponent(usrName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLoginCall, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnRegister)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnLoginCall))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        midLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        butikMid.add(midLogin, "card3");

        midRegister.setBackground(resourceMap.getColor("midRegister.background")); // NOI18N
        midRegister.setName("midRegister"); // NOI18N
        midRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        surName.setText(resourceMap.getString("surName.text")); // NOI18N
        surName.setName("surName"); // NOI18N

        name.setName("name"); // NOI18N

        userName.setName("userName"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        passChk.setText(resourceMap.getString("passChk.text")); // NOI18N
        passChk.setName("passChk"); // NOI18N

        pass.setText(resourceMap.getString("pass.text")); // NOI18N
        pass.setName("pass"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(surName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passChk, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(surName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passChk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        midRegister.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        butikMid.add(midRegister, "card4");

        midHistorik.setBackground(resourceMap.getColor("midHistorik.background")); // NOI18N
        midHistorik.setName("midHistorik"); // NOI18N
        midHistorik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setName("jSeparator1"); // NOI18N
        midHistorik.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 2560, -1));

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        tblFavCart.setFont(resourceMap.getFont("tblFavCart.font")); // NOI18N
        tblFavCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produkt", "Mängd", "Pris"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFavCart.setName("tblFavCart"); // NOI18N
        jScrollPane5.setViewportView(tblFavCart);
        tblFavCart.getColumnModel().getColumn(0).setResizable(false);
        tblFavCart.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblFavCart.columnModel.title0")); // NOI18N
        tblFavCart.getColumnModel().getColumn(1).setResizable(false);
        tblFavCart.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblFavCart.columnModel.title1")); // NOI18N
        tblFavCart.getColumnModel().getColumn(2).setResizable(false);
        tblFavCart.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblFavCart.columnModel.title2")); // NOI18N

        midHistorik.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 304, 370, 207));

        btnAddToCart.setFont(resourceMap.getFont("btnAddToCart.font")); // NOI18N
        btnAddToCart.setText(resourceMap.getString("btnAddToCart.text")); // NOI18N
        btnAddToCart.setName("btnAddToCart"); // NOI18N
        midHistorik.add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 157, 33));

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        midHistorik.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 265, -1, 30));

        fieldFavCartName.setText(resourceMap.getString("fieldFavCartName.text")); // NOI18N
        fieldFavCartName.setName("fieldFavCartName"); // NOI18N
        midHistorik.add(fieldFavCartName, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 273, 220, -1));

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        favCarts.setName("favCarts"); // NOI18N
        jScrollPane9.setViewportView(favCarts);

        midHistorik.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 300, 150));

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        oldCarts.setName("oldCarts"); // NOI18N
        jScrollPane10.setViewportView(oldCarts);

        midHistorik.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 150));

        addFavCart.setIcon(resourceMap.getIcon("addFavCart.icon")); // NOI18N
        addFavCart.setText(resourceMap.getString("addFavCart.text")); // NOI18N
        addFavCart.setName("addFavCart"); // NOI18N
        addFavCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFavCartMouseClicked(evt);
            }
        });
        midHistorik.add(addFavCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        removeFavCart.setIcon(resourceMap.getIcon("removeFavCart.icon")); // NOI18N
        removeFavCart.setText(resourceMap.getString("removeFavCart.text")); // NOI18N
        removeFavCart.setName("removeFavCart"); // NOI18N
        removeFavCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeFavCartMouseClicked(evt);
            }
        });
        midHistorik.add(removeFavCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 120, -1));

        jLabel32.setFont(resourceMap.getFont("jLabel32.font")); // NOI18N
        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        midHistorik.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel33.setFont(resourceMap.getFont("jLabel33.font")); // NOI18N
        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N
        midHistorik.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        butikMid.add(midHistorik, "card5");

        panelButik.add(butikMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        mainBot.add(panelButik, "card2");

        panelCheckout1.setName("panelCheckout1"); // NOI18N
        panelCheckout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(resourceMap.getFont("jLabel25.font")); // NOI18N
        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        panelCheckout1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        checkout1Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produkt", "Mängd", "Pris/Mängd", "Pris"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkout1Cart.setColumnSelectionAllowed(true);
        checkout1Cart.setName("checkout1Cart"); // NOI18N
        checkout1Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkout1CartMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(checkout1Cart);
        checkout1Cart.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        checkout1Cart.getColumnModel().getColumn(0).setResizable(false);
        checkout1Cart.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("checkout1Cart.columnModel.title0")); // NOI18N
        checkout1Cart.getColumnModel().getColumn(1).setResizable(false);
        checkout1Cart.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("checkout1Cart.columnModel.title1")); // NOI18N
        checkout1Cart.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("checkout1Cart.columnModel.title2")); // NOI18N
        checkout1Cart.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("checkout1Cart.columnModel.title3")); // NOI18N

        panelCheckout1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 397));

        startPayment.setFont(resourceMap.getFont("startPayment.font")); // NOI18N
        startPayment.setText(resourceMap.getString("startPayment.text")); // NOI18N
        startPayment.setName("startPayment"); // NOI18N
        startPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPaymentActionPerformed(evt);
            }
        });
        panelCheckout1.add(startPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 155, 30));

        checkoutProduct.setName("checkoutProduct"); // NOI18N
        panelCheckout1.add(checkoutProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        mainBot.add(panelCheckout1, "card3");

        panelCheckout2.setName("panelCheckout2"); // NOI18N
        panelCheckout2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setName("jPanel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        panelCheckout2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 52, -1, -1));

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 11, -1, -1));

        payName.setText(resourceMap.getString("payName.text")); // NOI18N
        payName.setName("payName"); // NOI18N
        jPanel5.add(payName, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 46, 153, -1));

        paySurname.setName("paySurname"); // NOI18N
        jPanel5.add(paySurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 72, 153, -1));

        payAdress.setName("payAdress"); // NOI18N
        jPanel5.add(payAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 98, 153, -1));

        payPostal.setName("payPostal"); // NOI18N
        jPanel5.add(payPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 124, 153, -1));

        payArea.setName("payArea"); // NOI18N
        jPanel5.add(payArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 150, 153, -1));

        payPhone.setName("payPhone"); // NOI18N
        jPanel5.add(payPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 176, 153, -1));

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 49, -1, -1));

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 75, -1, -1));

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 101, -1, -1));

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 127, -1, -1));

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 153, -1, -1));

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 176, -1, -1));

        panelCheckout2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jPanel6.setName("jPanel6"); // NOI18N

        jLabel19.setFont(resourceMap.getFont("jLabel19.font")); // NOI18N
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        payCardholder.setName("payCardholder"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        payCard.setName("payCard"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        payCvc.setName("payCvc"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        payExpireMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        payExpireMonth.setName("payExpireMonth"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        payExpireYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        payExpireYear.setName("payExpireYear"); // NOI18N

        payCardType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mastercard", "VISA" }));
        payCardType.setName("payCardType"); // NOI18N

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel19))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payCard, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(payExpireMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addGap(4, 4, 4)
                                .addComponent(payExpireYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(payCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payCardholder, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payCardholder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(payExpireMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(payExpireYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        panelCheckout2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 510, 190));

        btnFinishBuy.setFont(resourceMap.getFont("btnFinishBuy.font")); // NOI18N
        btnFinishBuy.setText(resourceMap.getString("btnFinishBuy.text")); // NOI18N
        btnFinishBuy.setName("btnFinishBuy"); // NOI18N
        btnFinishBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishBuyActionPerformed(evt);
            }
        });
        panelCheckout2.add(btnFinishBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 359, 145, 47));

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(resourceMap.getFont("jTextArea1.font")); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane6.setViewportView(jTextArea1);

        panelCheckout2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 103, 338, 220));

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        panelCheckout2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 70, -1, -1));

        payAccept.setText(resourceMap.getString("payAccept.text")); // NOI18N
        payAccept.setName("payAccept"); // NOI18N
        panelCheckout2.add(payAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 330, -1, -1));

        mainBot.add(panelCheckout2, "card5");

        panelCheckout3.setName("panelCheckout3"); // NOI18N

        jLabel27.setFont(resourceMap.getFont("jLabel27.font")); // NOI18N
        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        checkout3Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produkt", "Mängd", "Pris/Mängd", "Pris"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkout3Cart.setName("checkout3Cart"); // NOI18N
        jScrollPane8.setViewportView(checkout3Cart);
        checkout3Cart.getColumnModel().getColumn(0).setResizable(false);
        checkout3Cart.getColumnModel().getColumn(1).setResizable(false);

        btnGoHome.setFont(resourceMap.getFont("btnGoHome.font")); // NOI18N
        btnGoHome.setText(resourceMap.getString("btnGoHome.text")); // NOI18N
        btnGoHome.setName("btnGoHome"); // NOI18N
        btnGoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoHomeActionPerformed(evt);
            }
        });

        jLabel28.setFont(resourceMap.getFont("jLabel28.font")); // NOI18N
        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        javax.swing.GroupLayout panelCheckout3Layout = new javax.swing.GroupLayout(panelCheckout3);
        panelCheckout3.setLayout(panelCheckout3Layout);
        panelCheckout3Layout.setHorizontalGroup(
            panelCheckout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckout3Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addGroup(panelCheckout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckout3Layout.createSequentialGroup()
                        .addGroup(panelCheckout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(panelCheckout3Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(btnGoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckout3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(469, 469, 469))))
        );
        panelCheckout3Layout.setVerticalGroup(
            panelCheckout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckout3Layout.createSequentialGroup()
                .addGroup(panelCheckout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCheckout3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCheckout3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
        );

        mainBot.add(panelCheckout3, "card4");

        mainPanel.add(mainBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, 1359, 550));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 190, -1));

        productWindow1.setName("productWindow1"); // NOI18N

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    
    showRegisterPage();
    
}//GEN-LAST:event_btnRegisterActionPerformed

private void startPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPaymentActionPerformed
    controller.showPaymentPage();
}//GEN-LAST:event_startPaymentActionPerformed

private void btnFinishBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishBuyActionPerformed
    
    /*
    Order order = new Order();
    order.setItems( IMatDataHandler.getInstance().getShoppingCart().getItems() );
    order.setDate( new Date() );
    order.setOrderNumber( 1 );
     */
    
    CardType cardType = CardType.NoChosen;
    
    if( ((String)payCardType.getSelectedItem()).equals("Mastercard") )
        cardType = CardType.MasterCard;
    else if( ((String)payCardType.getSelectedItem()).equals("VISA") )
        cardType = CardType.VISA;
    
    PaymentInfo pInfo = new PaymentInfo(
                payName.getText(),
                paySurname.getText(),
                payAdress.getText(),
                payPostal.getText(),
                payArea.getText(),
                payPhone.getText(),
                cardType,
                payCard.getText(),
                payCardholder.getText(),
                Integer.parseInt( payCvc.getText() ),
                Integer.parseInt( (String)payExpireMonth.getSelectedItem() ),
                Integer.parseInt( (String)payExpireYear.getSelectedItem()) );
    
    //controller.finishPayment()
    
    showFinishedPaymentPage( IMatDataHandler.getInstance().placeOrder() );
}//GEN-LAST:event_btnFinishBuyActionPerformed

private void btnGoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoHomeActionPerformed
    showMainShoppingPage();
}//GEN-LAST:event_btnGoHomeActionPerformed

private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
    controller.showCategory( CategoryHandler.stringToCategory(  jTree1.getLastSelectedPathComponent().toString()) );
}//GEN-LAST:event_jTree1MouseClicked

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    if(name.getText().length()>0&&surName.getText().length()>0&&userName.getText().length()>0&&pass.getText().length()>3&&passChk.getText().equals(pass.getText()))
    {
        System.out.println("Yes hello this is Patrick.");
        if( !UserHandler.getInstance().registerUser(name.getText(), surName.getText(), userName.getText(), pass.getText()) ) {
            //Tell user username already exists
            return;
        }
        showMainShoppingPage();
            
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void btnLoginCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCallActionPerformed
    UserHandler.getInstance().login(usrName.getText(), pswd.getText());
}//GEN-LAST:event_btnLoginCallActionPerformed

private void checkout1CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkout1CartMouseClicked
    
    checkoutProduct.hideFav();
    checkoutProduct.setBtnText("Uppdatera Kundvagn");
    
    Product p = IMatDataHandler.getInstance().getShoppingCart().getItems().get(checkout1Cart.getSelectedRows()[0]).getProduct();
    
    //checkout1Cart.getSelectedRows()[0];
    checkoutProduct.setProduct( p );
    checkoutProduct.hideFav();
    
}//GEN-LAST:event_checkout1CartMouseClicked

private void btnHistorikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorikMouseClicked
    showEarlierOrdersPage();
    setFavoriteCartList(null);
}//GEN-LAST:event_btnHistorikMouseClicked

private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    showLoginPage();
}//GEN-LAST:event_btnLoginMouseClicked

private void btnButikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnButikMouseClicked
    showMainShoppingPage();
}//GEN-LAST:event_btnButikMouseClicked

private void btnHistorikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorikMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_btnHistorikMouseEntered

private void btnEmptyBasketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptyBasketMouseClicked
    controller.emptyShoppingCart();
}//GEN-LAST:event_btnEmptyBasketMouseClicked

private void btnKassanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKassanMouseClicked
    showCheckoutPage();
    checkoutProduct.hideFav();
    checkoutProduct.setBtnText("Uppdatera Kundvagn");
}//GEN-LAST:event_btnKassanMouseClicked

private void btnEmptyBasket1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptyBasket1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_btnEmptyBasket1MouseClicked

private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
    showCheckoutPage();
    checkoutProduct.hideFav();
    checkoutProduct.setBtnText("Uppdatera Kundvagn");
}//GEN-LAST:event_jLabel26MouseClicked

private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
    controller.searchFor( fieldSearch.getText() );
}//GEN-LAST:event_jLabel29MouseClicked

private void addFavCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFavCartMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_addFavCartMouseClicked

private void removeFavCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFavCartMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_removeFavCartMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addFavCart;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JLabel btnButik;
    private javax.swing.JLabel btnEmptyBasket;
    private javax.swing.JLabel btnEmptyBasket1;
    private javax.swing.JButton btnFinishBuy;
    private javax.swing.JButton btnGoHome;
    private javax.swing.JLabel btnHistorik;
    private javax.swing.JLabel btnKassan;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JButton btnLoginCall;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel butikLeft;
    private javax.swing.JScrollPane butikList;
    private javax.swing.JPanel butikMid;
    private javax.swing.JPanel butikRight;
    private javax.swing.JLayeredPane butikSwitcher;
    private javax.swing.JTable checkout1Cart;
    private javax.swing.JTable checkout3Cart;
    private imat.productWindow checkoutProduct;
    private javax.swing.JList favCarts;
    private javax.swing.JTextField fieldFavCartName;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable kundvagn;
    private javax.swing.JLabel logoTop;
    private javax.swing.JPanel mainBot;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainTop;
    private javax.swing.JPanel midButik;
    private javax.swing.JPanel midHistorik;
    private javax.swing.JPanel midLogin;
    private javax.swing.JPanel midRegister;
    private javax.swing.JTextField name;
    private javax.swing.JList oldCarts;
    private javax.swing.JPanel panelButik;
    private javax.swing.JPanel panelCheckout1;
    private javax.swing.JPanel panelCheckout2;
    private javax.swing.JPanel panelCheckout3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passChk;
    private javax.swing.JCheckBox payAccept;
    private javax.swing.JTextField payAdress;
    private javax.swing.JTextField payArea;
    private javax.swing.JTextField payCard;
    private javax.swing.JComboBox payCardType;
    private javax.swing.JTextField payCardholder;
    private javax.swing.JTextField payCvc;
    private javax.swing.JComboBox payExpireMonth;
    private javax.swing.JComboBox payExpireYear;
    private javax.swing.JTextField payName;
    private javax.swing.JTextField payPhone;
    private javax.swing.JTextField payPostal;
    private javax.swing.JTextField paySurname;
    private imat.productWindow productWindow;
    private imat.productWindow productWindow1;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JLabel removeFavCart;
    private javax.swing.JButton startPayment;
    private javax.swing.JTextField surName;
    private javax.swing.JTable tblFavCart;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField usrName;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
    
    public void addProduct( Product p, double amount) {
        controller.addProduct(p, amount);
    }
    
    public void updateCart( Product p, double a ) {
        controller.updateCart(p, a);
    }

    public ShoppingCartListener getShoppingCartListener() {
        return cartListener;
    }

    public void setFavoriteCartList(List<String> cartNames) {
        
        List<Order> orders = IMatDataHandler.getInstance().getOrders();
        SimpleDateFormat dateformatMMDDYYYY = new SimpleDateFormat("MM/dd-yyyy hh:mm");
        
        DefaultListModel model = new DefaultListModel();
        oldCarts.setModel(model);
        
        Iterator it = orders.iterator();
        while(it.hasNext())
        {
            Order o = (Order)it.next();
            StringBuilder nowMMDDYYYY = new StringBuilder( dateformatMMDDYYYY.format( o.getDate() ) );
            int pos = oldCarts.getModel().getSize();
            model.add(pos, nowMMDDYYYY );
            System.out.println( nowMMDDYYYY );
        }
        
    }

    public void displaySelectedCart(NamedOrder order) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void closeProductWindow() {
        butikSwitcher.moveToFront( butikList );
        butikSwitcher.moveToBack( productWindow );
    }

    public void openProductWindow(Product product) {
        if(product == null)
            product = lastProduct;
        else
            lastProduct = product;
        productWindow.setProduct( product );
        butikSwitcher.moveToFront( productWindow );
        butikSwitcher.moveToBack( butikList );
    }

    public void showFinishedPaymentPage(Order order) {
        //IMatDataHandler.getInstance().p
        panelCheckout1.setVisible(false);
        panelCheckout2.setVisible(false);
        panelCheckout3.setVisible(true);
    }

    public void termsNotAccepted() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void noSuchUser() {
        // TODO Show information that no such user is registered
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void openCheckoutProductWindow(Product product) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public boolean confirmClearShoppingCart() {
        kundvagn.removeAll();
        return true;
    }

    void showLastProducts() {
        showProducts(lastProducts);
    }
    
    public void showProducts(List<Product> products) {
        lastProducts = products;
        //List products in the main shop view
        
        //Create inner panel to store shit
        JPanel innerPanel = new JPanel();
        //Set layout to flowlayout to get nice listing
        innerPanel.setLayout( new FlowLayout(FlowLayout.LEFT) );
        innerPanel.setPreferredSize( new Dimension(0,0) );  //Panel won't scale properly unless we do this
        //Add inner panel
        butikList.getViewport().add(innerPanel);
        
        //Iterate through list 
        Iterator it = products.iterator();
        while( it.hasNext() )
        {
            Product element = (Product) it.next();
            
            //Add product to panel
            shopItem i = new shopItem( element );
            if(isFavorite(element))
                i.setBorder( BorderFactory.createLineBorder(Color.red));
                
            innerPanel.add( i );
        }
        
        //Add the items
        
        //GOD DAMN IT
        butikList.setPreferredSize( new Dimension(0,1050));
        innerPanel.revalidate();
        innerPanel.validate();
        butikList.revalidate();
        butikList.validate();  
        
    }
    
    public boolean isFavorite( Product p ) {
        return controller.isFavorite( p );
    }
    
    public void toggleFavorite( Product p ) {
        controller.toggleFavorite( p );
    }

    public void showCheckoutPage() {
        panelButik.setVisible(false);
        panelCheckout1.setVisible(true);
        panelCheckout2.setVisible(false);
        panelCheckout3.setVisible(false);
    }

    public void showEarlierOrdersPage() {
        btnHistorik.setIcon( new ImageIcon("build/classes/imat/resources/historikSelected.png") );
        btnLogin.setIcon( new ImageIcon("build/classes/imat/resources/loggain.png") );
        btnButik.setIcon( new ImageIcon("build/classes/imat/resources/butik.png") );
        midButik.setVisible( false );
        midLogin.setVisible( false );
        midRegister.setVisible( false );
        midHistorik.setVisible( true );
    }

    public void showLoginPage() {
        btnHistorik.setIcon( new ImageIcon("build/classes/imat/resources/historik.png") );
        btnLogin.setIcon( new ImageIcon("build/classes/imat/resources/loggainSelected.png") );
        btnButik.setIcon( new ImageIcon("build/classes/imat/resources/butik.png") );
        panelCheckout1.setVisible(false);
        panelCheckout2.setVisible(false);
        panelCheckout3.setVisible(false);
        midButik.setVisible( false );
        midLogin.setVisible( true );
        midRegister.setVisible( false );
        midHistorik.setVisible( false );
    }

    public void showPaymentPage(PaymentInfo paymentInfo) {
        panelCheckout1.setVisible(false);
        panelCheckout2.setVisible(true);
        panelCheckout3.setVisible(false);
    }

    public void showRegisterPage() {
        midButik.setVisible( false );
        midLogin.setVisible( false );
        midRegister.setVisible( true );
        midHistorik.setVisible( false );
    }

    public void showWelcomePage() {
        cartListener.shoppingCartChanged(); //TODO: Fy skäms!
    }

    public void passwordsNotMatching() {
        // TODO Show information that the password and repeated passwords aren't matching.
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void showMainShoppingPage() {
        btnHistorik.setIcon( new ImageIcon("build/classes/imat/resources/historik.png") );
        btnLogin.setIcon( new ImageIcon("build/classes/imat/resources/loggain.png") );
        btnButik.setIcon( new ImageIcon("build/classes/imat/resources/butikSelected.png") );
        panelCheckout1.setVisible(false);
        panelCheckout2.setVisible(false);
        panelCheckout3.setVisible(false);
        midButik.setVisible( true );
        midLogin.setVisible( false );
        midRegister.setVisible( false );
        midHistorik.setVisible( false );
    }

    public void setLoggedInUser(IMatUser loggedInUser) {
        // TODO A new user has logged in, update "inloggad som" and so on.
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
