/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * itemPop.java
 *
 * Created on Feb 29, 2012, 1:11:18 AM
 */
package imat;

import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Fewes
 */
public class productWindow extends javax.swing.JPanel {

    double realPrice;
    Product prod;
    
    /** Creates new form itemPop */
    public productWindow() {
        initComponents();
    }
    
    public void setProduct( Product p ){
        
        IMatView view = IMatView.getView();     
        
        //Unhide close button
        btnCloseProductWindow.setVisible( true );
        
        if(view.isFavorite(p))
            iconFav.setIcon( new ImageIcon("build/classes/imat/resources/starred.png") );
        else
            iconFav.setIcon( new ImageIcon("build/classes/imat/resources/unstarred.png") );
         
        
        //Check for decimal in price and deal with it accordingly
        double dprice = p.getPrice();
        realPrice = p.getPrice();
        prod = p;
        priceTotal.setText( realPrice + " kr" );
        String pris;
        if( (int)dprice == dprice )
            pris = ""+(int)dprice;
        else
            pris = dprice + "0";
        
        name.setText( p.getName() );
        price.setText( pris + " kr/" + p.getUnitSuffix() );
        image.setIcon( IMatDataHandler.getInstance().getImageIcon(p,358,240) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        spnrAmount = new javax.swing.JSpinner( new SpinnerNumberModel(1, 1, 99,

            1) );
    lblTotal = new javax.swing.JLabel();
    priceTotal = new javax.swing.JLabel();
    iconFav = new javax.swing.JLabel();
    jToggleButton1 = new javax.swing.JToggleButton();
    btnCloseProductWindow = new javax.swing.JToggleButton();

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(productWindow.class);
    setBackground(resourceMap.getColor("Form.background")); // NOI18N
    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    setName("Form"); // NOI18N

    image.setIcon(resourceMap.getIcon("image.icon")); // NOI18N
    image.setText(resourceMap.getString("image.text")); // NOI18N
    image.setName("image"); // NOI18N

    name.setFont(resourceMap.getFont("name.font")); // NOI18N
    name.setText(resourceMap.getString("name.text")); // NOI18N
    name.setName("name"); // NOI18N

    price.setFont(resourceMap.getFont("price.font")); // NOI18N
    price.setText(resourceMap.getString("price.text")); // NOI18N
    price.setName("price"); // NOI18N

    lblAmount.setFont(resourceMap.getFont("lblAmount.font")); // NOI18N
    lblAmount.setText(resourceMap.getString("lblAmount.text")); // NOI18N
    lblAmount.setName("lblAmount"); // NOI18N

    spnrAmount.setName("spnrAmount"); // NOI18N
    spnrAmount.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spnrAmountStateChanged(evt);
        }
    });

    lblTotal.setFont(resourceMap.getFont("lblTotal.font")); // NOI18N
    lblTotal.setText(resourceMap.getString("lblTotal.text")); // NOI18N
    lblTotal.setName("lblTotal"); // NOI18N

    priceTotal.setFont(resourceMap.getFont("priceTotal.font")); // NOI18N
    priceTotal.setText(resourceMap.getString("priceTotal.text")); // NOI18N
    priceTotal.setName("priceTotal"); // NOI18N

    iconFav.setIcon(resourceMap.getIcon("iconFav.icon")); // NOI18N
    iconFav.setText(resourceMap.getString("iconFav.text")); // NOI18N
    iconFav.setName("iconFav"); // NOI18N
    iconFav.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            iconFavMouseClicked(evt);
        }
    });

    jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
    jToggleButton1.setName("jToggleButton1"); // NOI18N
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton1ActionPerformed(evt);
        }
    });

    btnCloseProductWindow.setIcon(resourceMap.getIcon("btnCloseProductWindow.icon")); // NOI18N
    btnCloseProductWindow.setText(resourceMap.getString("btnCloseProductWindow.text")); // NOI18N
    btnCloseProductWindow.setName("btnCloseProductWindow"); // NOI18N
    btnCloseProductWindow.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnCloseProductWindowMousePressed(evt);
        }
    });
    btnCloseProductWindow.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseProductWindowActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addComponent(name)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(iconFav)
            .addContainerGap(66, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(159, Short.MAX_VALUE)
            .addComponent(price)
            .addGap(157, 157, 157))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(72, 72, 72)
            .addComponent(lblAmount)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(spnrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
            .addComponent(lblTotal)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(priceTotal)
            .addGap(56, 56, 56))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(319, Short.MAX_VALUE)
            .addComponent(btnCloseProductWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(btnCloseProductWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(image)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(name)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(price))
                .addComponent(iconFav))
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotal)
                .addComponent(priceTotal)
                .addComponent(lblAmount)
                .addComponent(spnrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

private void btnCloseProductWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseProductWindowActionPerformed
    IMatView.getView().closeProductWindow();
    //Hide close button
    btnCloseProductWindow.setVisible( false );
}//GEN-LAST:event_btnCloseProductWindowActionPerformed

private void btnCloseProductWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseProductWindowMousePressed
// TODO add your handling code here:
}//GEN-LAST:event_btnCloseProductWindowMousePressed

private void spnrAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnrAmountStateChanged
    priceTotal.setText( "" + realPrice * Integer.parseInt( spnrAmount.getValue().toString() ) + " kr" );
}//GEN-LAST:event_spnrAmountStateChanged

private void iconFavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFavMouseClicked
    IMatView.getView().toggleFavorite( prod );
    if(IMatView.getView().isFavorite(prod))
            iconFav.setIcon( new ImageIcon("build/classes/imat/resources/starred.png") );
        else
            iconFav.setIcon( new ImageIcon("build/classes/imat/resources/unstarred.png") );
}//GEN-LAST:event_iconFavMouseClicked

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    IMatView.getView().addProduct(prod, Integer.parseInt( spnrAmount.getValue().toString() ));
}//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCloseProductWindow;
    private javax.swing.JLabel iconFav;
    private javax.swing.JLabel image;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel priceTotal;
    private javax.swing.JSpinner spnrAmount;
    // End of variables declaration//GEN-END:variables
}
