/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * shopItem.java
 *
 * Created on Feb 28, 2012, 10:19:10 AM
 */
package imat;

import java.awt.event.*;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author felixw
 */
public class shopItem extends javax.swing.JPanel {

    /** Creates new form shopItem */
    public shopItem( final Product p ) {
        initComponents();
        
        addMouseListener(new MouseAdapter() { 
            public void mousePressed(MouseEvent me) {
                IMatView.getView().openProductWindow( p );
            } 
        }); 
        
        //Check for decimal in price and deal with it accordingly
        double dprice = p.getPrice();
        String price;
        if( (int)dprice == dprice )
            price = ""+(int)dprice;
        else
            price = dprice + "0";
        
        namn.setText( p.getName() );
        pris.setText( price + " kr/" + p.getUnitSuffix() );
        bild.setIcon( IMatDataHandler.getInstance().getImageIcon(p,120,90) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namn = new javax.swing.JLabel();
        pris = new javax.swing.JLabel();
        bild = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(shopItem.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        namn.setFont(resourceMap.getFont("namn.font")); // NOI18N
        namn.setText(resourceMap.getString("namn.text")); // NOI18N
        namn.setAlignmentX(0.5F);
        namn.setName("namn"); // NOI18N

        pris.setText(resourceMap.getString("pris.text")); // NOI18N
        pris.setAlignmentX(0.5F);
        pris.setName("pris"); // NOI18N

        bild.setIcon(resourceMap.getIcon("bild.icon")); // NOI18N
        bild.setText(resourceMap.getString("bild.text")); // NOI18N
        bild.setName("bild"); // NOI18N
        bild.setPreferredSize(new java.awt.Dimension(120, 90));
        bild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bildFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pris))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(namn)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pris)
                .addGap(18, 18, 18)
                .addComponent(bild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

}//GEN-LAST:event_formFocusLost

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_formMouseClicked

private void bildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bildFocusLost

}//GEN-LAST:event_bildFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bild;
    private javax.swing.JLabel namn;
    private javax.swing.JLabel pris;
    // End of variables declaration//GEN-END:variables
}
